version: '3.8'

volumes:
  db-data:

services:
  app:
    build: .
    image: springio/smartgym:0.0.3b
    container_name: smartgym
    depends_on:
      - db
    restart: always
    ports:
      - "8083-8083"
    networks:
      - myNetwork
  db:
    image: postgres:13.1-alpine
    container_name: gym_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p123
      POSTGRES_DB: db_smartgym
      PGDATA: db-data:/var/lib/postresql/data
    volumes:
      # Data
      - db-data:/var/lib/postresql/data
      # Scripts
      - ./scripts:/scripts
      # - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - myNetwork
  pgadmin:
    image: dpage/pgadmin4:6.13
    container_name: pgadmin4c
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: p123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
